<style lang="less" scoped>
  @import "./roleStaffList.less";
</style>
<template>
  <transition name="fade">
    <div class="role-staff-list-container tzx-slide-right-window-container have-table-container">
      <div class="body" ref="slideRightBody">
        <div class="head">
          <h3 class="title">{{ role.roleName }} 服务人员列表</h3>
          <i class="saas iconfont saas-nav-closehover close-icon-btn" @click="close"></i>
        </div>
        <div class="main">
          <div class="search-container">
            <el-input placeholder="请输入姓名或账号快速查找" v-model="searchKeyWords" clearable @blur="searchKeyWords = searchKeyWords.trim()">
              <template slot="append">
                <i slot="suffix" class="saas iconfont saas-seach" @click="search"></i>
              </template>
            </el-input>
          </div>
          <div class="table-container tzx-table-container">
            <el-table ref="empsTable" :data="tmpRoleStaffList" style="width: 100%;" highlight-current-row tooltip-effect='light' empty-text=" ">
              <el-table-column prop='empAccount' label="账号" width="80px" show-overflow-tooltip></el-table-column>
              <el-table-column prop='empJob' label="职位" width="80px" show-overflow-tooltip></el-table-column>
              <el-table-column label="状态"
                prop="tag"
                width="80px"
                :filters="[{ text: '有效', value: '1' }, { text: '无效', value: '0' }]"
                :filter-method="filterValidState"
                :filter-multiple="false"
                filter-placement="bottom-start">
                <template slot-scope="scope">
                  <el-tag v-if='scope.row.state === "1"' type="success">有效</el-tag>
                  <el-tag v-else type="danger">无效</el-tag>
                </template>
              </el-table-column>
              <el-table-column label="姓名/手机号">
                <template slot-scope="scope">
                  <div>{{scope.row.empName}}</div>
                  <div>{{scope.row.phone}}</div>
                </template>
              </el-table-column>
            </el-table>

          </div>
        </div>
        <div class="statistics">
            {{ role.roleName }} 角色人员合计：{{roleStaffList.length}}人
        </div>
      </div>
    </div>
  </transition>
</template>
<script>
  import '../../../../assets/less/tzx-slide-right-window.css'
  export default {
    created () {
      /*
      // 假数据
      let result = {
        code: '0',
        msg: '操作成功！',
        data: [
          {
            empId: null,
            empName: '呵呵呵',
            empAccount: 'hehehe',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '15801054788',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'zc',
            empAccount: 'zc',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13827292829',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '0002',
            empAccount: '0002',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '0',
            phone: '13900200200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scottyz',
            empAccount: 'scottyz',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'jzf',
            empAccount: 'jzf',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15801526200',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '柳慧',
            empAccount: 'liuhui15',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13612324343',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'jxu',
            empAccount: 'jxu',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15947236631',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '张三',
            empAccount: 'zhangsan',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13555545382',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'lee',
            empAccount: '0007',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18701137212',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '鹏',
            empAccount: 'dpadmin',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13112122121',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '高健',
            empAccount: 'gaj',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15801655522',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'jxyuuid',
            empAccount: 'jxyuuid',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '17777777777',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '王国照',
            empAccount: 'root',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15801054364',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '王国照',
            empAccount: 'hehe',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15801054364',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'k',
            empAccount: 'k',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13653434225',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'dd',
            empAccount: 'der',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15099999989',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'ss1',
            empAccount: 'ss1',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '李四',
            empAccount: 'lisi',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '17777777778',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '李四1',
            empAccount: 'lisi1',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '17777777773',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '肖凯',
            empAccount: 'xiaokai',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18616221827',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'xue',
            empAccount: 'adm',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15098765438',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '王伟强测试',
            empAccount: 'wwq',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18608063720',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'scott',
            empAccount: '15292866807',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15292866807',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'xiaokaitest',
            empAccount: 'xiao123',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13145678907',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '杨文彦二号',
            empAccount: 'yangdtms',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18311386905',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '杨文彦一号',
            empAccount: 'yangfile',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18311386905',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '刘志成',
            empAccount: 'liuzhicheng',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18618143404',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'shouyin2',
            empAccount: 'shouyin2',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18311382222',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'shouyin1',
            empAccount: 'shouyin1',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '18311381111',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: '孔明1',
            empAccount: 'kxm1',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '15858585858',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          },
          {
            empId: null,
            empName: 'l',
            empAccount: 'l',
            assword: null,
            birthday: null,
            empJob: 'IT管理员dd',
            empJobState: null,
            state: '1',
            phone: '13333333333',
            empCode: null,
            createDate: null,
            createPerson: null,
            jobTitle: null,
            jobCode: null,
            stateName: null,
            rolesName: null,
            sex: null,
            paperNo: null,
            education: null,
            idCard: null,
            storeId: null,
            userAuthorityId: null,
            rolesId: null,
            userAuthorityRolesId: null,
            organCode: null,
            storeIds: null
          }
        ]
      }
      this.roleStaffList = result.data
      // console.log(this.roleStaffList)

      // 拷贝数组
      this.copy(this.roleStaffList, this.tmpRoleStaffList)
      //
      */
      // 发起请求获取角色人员列表
      this.getRoleStaffListAjax()
    },
    mounted () {
      if (this.showSlideRightBody) {
        this.showBody()
      }
    },
    props: ['role', 'showRoleStaffList'],
    data () {
      return {
        showSlideRightBody: this.showRoleStaffList,
        roleStaffList: [], // 角色人员列表
        tmpRoleStaffList: [], // 临时列表
        searchKeyWords: '' // 搜索关键词
      }
    },
    methods: {
      getRoleStaffListAjax () {
        this.$http
          .post('/api/role/roles/loadRolesToEmployeeInfo', {roleId: this.role.id})
          .then(res => {
            if (res.data.code === '0') {
              // 初始化数据
              this.roleStaffList = res.data.data
              // 拷贝数组
              this.copy(this.roleStaffList, this.tmpRoleStaffList)
            } else {
              this.$message({ type: 'error', message: res.data.msg })
            }
          })
          .catch(err => {
            this.$message({ type: 'error', message: err.msg })
          })
      },
      showBody () { // 显示body
        this.$refs.slideRightBody.style.right = 0
        this.$refs.slideRightBody.style.opacity = 1
      },
      close: function () {
        this.$emit('close')
      },
      filterValidState (value, row) { // 有效/无效状态过滤
        console.log(value, row)
        return row.state === value
      },
      search () {
        if (this.searchKeyWords.trim() !== '') {
          let searchResult = []
          for (let i = 0; i < this.roleStaffList.length; i++) {
            let emp = this.roleStaffList[i]
            if (emp.empName === this.searchKeyWords || emp.empAccount === this.searchKeyWords) {
              searchResult.push(emp)
            }
          }
          this.tmpRoleStaffList = searchResult
        } else {
          this.tmpRoleStaffList = this.roleStaffList
        }
      },
      copy (srcArr, distArr) { // 数组拷贝
        for (let i = 0; i < srcArr.length; i++) {
          let o = srcArr[i]
          let tmp = {}
          for (let k in o) {
            tmp[k] = o[k]
          }
          distArr.push(tmp)
        }
      }
    }
  }
</script>
